### ISSUE TITLE
Database grows continuously - nightly reports running but no record delete

### ISSUE THREAD

**Issue by bearbate** [nlmaca/Enecsys_Dashboard#1]
I don't know if I am alone but the database enecsys table is growing continuously. Now up to >200,000 lines since 27/1/17. Response is now **VERY** slow as a result.
Nightly reports is running but <b>$nrrows</b> always returns 0 even though the enecsys_report table is updated.
Tried running it from command line with debug variable echos but no clues as to problem source.
Cannot see anything wrong with mySQL queries.
Any ideas?

**Comment by nlmaca** [comment]
Hi Bearbate,
you are actually the first with this. I dont know why it doesn't delete. But as long as the nightly reports are valid, you can run this command from phpmyadmin or mysql commandline. This is what the cronjob does after the reports have been made:
DELETE FROM enecsys WHERE ts < NOW() - INTERVAL 3 DAY;

This should clean your enecsys table, without destroying the reports.
Since when are you running this version? and i assume you run it on an raspberry?

**Comment by bearbate** [comment]
Thanks.

I installed on 30th January this year. Have checked cron_nightly_report code and it is same as current on github, not corrupted.

Yes, it is on a raspberry pi.

I have been looking at this all day (it rained). Can’t figure it out but had got as far as deleting some records using query similar to your suggestion.

Have added debug code to try and trace what has happened and will report if problem found.

Regards

**Comment by bearbate** [comment]
$output->numrows returns 11 which is correct
It then produces the report and inserts into database table enecsys_report correctly
BUT **$nrrows** definitely returns 0
Hence deletion does not take place.
I can see why $nrrows will never get above 1 as it is inside the while loop and there is only 1 insertion per iteration. I cannot see why it returns 0 unless the loop fails on the last iteration.
I have added more debug code.
## 
**UPDATE: SOLVED**
The problem appears to be with line 13 query
"SELECT DATE_FORMAT( ts, '%Y-%m-%d' ) AS Date FROM enecsys WHERE ts < CURDATE() GROUP BY DATE ORDER BY `Date` DESC"

Date sort should be ORDER BY `Date` ASC
If you have >1 days of data but only yesterday needs a report update, the first iteration of the loop returns the number of days of reports needed, in this case only 1 day as previous reports exist.
After the first date, there are no reports needed so $nrrows returns 0 every time:

pi@solarpi:~ $ cd /var/www/html/enecsys/cron
pi@solarpi:/var/www/html/enecsys/cron $ sudo nano cron_nightly_reports.php
pi@solarpi:/var/www/html/enecsys/cron $ sudo php cron_nightly_reports.php
Number of rows in table enecsys = 11
date = 2017-02-27 : nrrows =  12
date = 2017-02-26 : nrrows =  0
date = 2017-02-25 : nrrows =  0
date = 2017-02-24 : nrrows =  0
date = 2017-02-23 : nrrows =  0
date = 2017-02-22 : nrrows =  0
date = 2017-02-21 : nrrows =  0
date = 2017-02-20 : nrrows =  0
date = 2017-02-19 : nrrows =  0
date = 2017-02-18 : nrrows =  0
date = 2017-02-17 : nrrows =  0
Number of rows affected, nrrows = 0
pi@solarpi:/var/www/html/enecsys/cron $ sudo nano cron_nightly_reports.php
--------------modified line 13 to "ASC" here-----------------------------------
pi@solarpi:/var/www/html/enecsys/cron $ sudo php cron_nightly_reports.php
Number of rows in table enecsys = 11
date = 2017-02-17 : nrrows =  0
date = 2017-02-18 : nrrows =  0
date = 2017-02-19 : nrrows =  0
date = 2017-02-20 : nrrows =  0
date = 2017-02-21 : nrrows =  0
date = 2017-02-22 : nrrows =  0
date = 2017-02-23 : nrrows =  0
date = 2017-02-24 : nrrows =  0
date = 2017-02-25 : nrrows =  0
date = 2017-02-26 : nrrows =  0
date = 2017-02-27 : nrrows =  12
Number of rows affected, nrrows = 12
Attempting to delete!
Number to delete = 66229
pi@solarpi:/var/www/html/enecsys/cron $

Am now examining why you need to find if deletions necessary before doing the delete as just deleteing them without the check seems to work ok as per your post above.
Regards and thanks again
Bearbate

**Comment by nlmaca** [comment]
Hi Bearbate, i didnt notice the difference at first in the query. will do some checking/debugging on it
thx.
although the delete process could be build better, but i ran out of time ;).

**Comment by bearbate** [comment]
The revised query has now been working perfectly for several days including the Feb/March transition:
Number of rows in table enecsys = 4
date = 2017-02-28 : nrrows =  0
date = 2017-03-01 : nrrows =  0
date = 2017-03-02 : nrrows =  0
date = 2017-03-03 : nrrows =  12
Number of rows affected, nrrows = 12
Attempting to delete!
Number to delete = 7848

I suggest that the change from DESCENDING to ASCENDING be made to the query in line 13.

I am now going to get this working on a Raspberry Pi Zero W.

Regards and thanks for your excellent software
Bearbate.

**Comment by nlmaca** [comment]
Hi Bearbate, 
Thx for the feedback and debugging!

im currently testing, but there is more to it. Your reaction got me thinking. For example my history table is updated, and i insert old data again in the enecsys table. the records will also remain, because no rows have been inserted when i run the cronjob again. Now the delete proces will ONLY start deleting when it has inserted (at least 1 record) rows into the history table. Although it should always be the case, I will also build in some debug output, in case you want to run it extra on the command line.

I will rebuild the delete proces. will do some extended testing on it, to make sure it works. Will update here if i fixed in a better (clean) way.

good luck with the Pi Zero. i wonder how you get the Ethernet connection though?

**Comment by nlmaca** [comment]
ok, got it rebuild, will have to get a recent database from my dad though. i don't have solar panels myself:). It's working with testdata.

1. get data from table which is older then currentdate
2. insert data into reports table (if not exists)
3. delete proces. first get the date from reports table, if exists in maintable (enecsys) then delete it. keep an overlap of 3 days. (in case of rpi errors, or if you have gateway/router issues)
4. extra check. get the latest date from the reports table. delete everything older then 7 days from that date

**Comment by nlmaca** [comment]
fixed this in hotfix 2. it is already included in the main package. only run the hotfix 2 if you have installed the dashboard before march 16. 
issue is solved

**Comment by bearbate** [comment]
Thanks for your effort, I will try it out. Re Pi - I am using the new Zero "W" which has wifi & bluetooth built in. See http://www.tel-me.info/

Regards
Bearbate
