### ISSUE TITLE
php5 no longer available on Debian strech, meaning installation fails.

### ISSUE THREAD

**Issue by Yarael-Poof** [nlmaca/Enecsys_Dashboard#2]
The 2.sudo_install_webserver.sh script does not work correctly since php5 is no longer available in Debian strech. I fixed this by replacing every instance of 'php5' with 'php7.0'. When it came to enabling mcrypt repacing 'php5enmod' with' phpenmod' Also, for some reason, I was also not prompted to enter MySQL root password and had to edit this manually. 
These links were useful 
https://packages.debian.org/stable/php/php
https://wiki.debian.org/PHP

Other than this the installation continued normally.

**Comment by nlmaca** [comment]
Hi,
Thx for your feedback. 
I am indeed aware of the new packages from raspberry. The complete installation was based on Weezy in 2015. Will see if i can update the package and installation manual for the latest package and php 7. I will have to rewrite some installation packages for this.

I don't know when that will be as time is always a bit of a problem :D.

**Comment by nlmaca** [comment]
hi,
i started a develop branch to rebuild some of the installation files and take your feedback into it. Will update this thread when the update is released. I might need some testers on this, because i don;t have solar panels myself
