### ISSUE TITLE
Current version of PHP 7.3.4 has deprecated mcrypt

### ISSUE THREAD

**Issue by sheppeybridge** [nlmaca/Enecsys_Dashboard#3]
Hi
I was trying to update my pi with your latest software (original version been running for years - but doesn't read the individual microinverters)  but the installation script 2.sudo_install_webserver.sh
has 
           sudo apt-get -y install apache2 php php-mcrypt php-mysql php-curl php-gd php-json mysql-server 

but this installs PHP V7.3.4 which has had php-mcrypt deprecated.  

So I edited the line as follows:

change line FROM
sudo apt-get -y install apache2 php php-mcrypt php-mysql php-curl php-gd php-json mysql-server 
TO

sudo apt-get -y install apache2 php7.1 php7.1-mcrypt php7.1-mysql php7.1-curl php7.1-gd php7.1-json mariadb-server

then you need to run 
sudo mysql_secure_installation 
and set the password with the one given in your script.
This then allowed the database to be created and I could carry on with the installation. All working now and great to be able to see the individual inverters details
Thanks

**Comment by nlmaca** [comment]
Hi Sheppeybridge, thx for the feedback and solution on this. 
The code and install scripts are indeed old at this time. 3+ years. My parents still run on the php 7.0 version. Sooner or later this problem would occur. 
There are other ways to compil the mcrypt extension, but i have to look into that. At this point i don't have any updates planned. 

Thx again for the feedback

**Comment by nlmaca** [comment]
Issue closed. New version is in progress.
