### ISSUE TITLE
No connection between gateway and Enecsys Dashboard

### ISSUE THREAD

**Issue by JanvdW304** [nlmaca/Enecsys_Dashboard#7]
My Enecsys gateway died some time ago. Recently I bought a second-hand one. I did a fresh installation of the RPI OS 64 bit image on a RPI4. Installation of Enecsys Dashboard went smooth, but I have connection problems between the Encesys gateway and Enecsys Dashboard.

UnitGate (a stand alone application) immediately receives the data from the inverters via the gateway, so the Enecsys gateway itself works fine. In first instance the remote server pointed to port 5040 of enecsysoutput.com (which results in a connection). If I change this to port 5040 of the RPI IP, the gateway remains offline.

What am I missing?

**Comment by nlmaca** [comment]
Which php version are you running? Because it is only running fine on php 7.4. php 8 is not supported.

**Comment by JanvdW304** [comment]
Great, I overlooked that: new RPI images are running PHP 8. After installing PHP 7.4 I have connection immediately. Thanks a lot!
